//Matías Medina y Nicolas Hobbins
package Interfaz;


public class Bienvenida extends javax.swing.JFrame {
    /**
     * Creates new form VentanaRegistroPuesto
     */
    public Bienvenida() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelBienvenida = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        jLabelNico = new javax.swing.JLabel();
        jLabelMati = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        JLabelBienvenida.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        JLabelBienvenida.setText("¡Bienvenido a Constructora Medins!");
        getContentPane().add(JLabelBienvenida);
        JLabelBienvenida.setBounds(30, 10, 300, 40);

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono.png"))); // NOI18N
        getContentPane().add(jLabelIcono);
        jLabelIcono.setBounds(120, 80, 130, 130);

        jLabelNico.setText("Nicolas Hobbins 267296");
        getContentPane().add(jLabelNico);
        jLabelNico.setBounds(40, 250, 140, 16);

        jLabelMati.setText("Matías Medina 302566");
        getContentPane().add(jLabelMati);
        jLabelMati.setBounds(210, 250, 140, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 420);

        setSize(new java.awt.Dimension(388, 354));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelBienvenida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelMati;
    private javax.swing.JLabel jLabelNico;
    // End of variables declaration//GEN-END:variables
}
