//Nicolas Hobbins y Matias Medina
package Interfaz;
import Dominio.*;

import java.util.ArrayList;
import javax.swing.*;

public class VentanaEstadoObra extends JFrame {
    private Sistema s;
    DefaultListModel<String> model = new DefaultListModel<>();
    DefaultListModel<String> model1 = new DefaultListModel<>();
    DefaultListModel<String> model2 = new DefaultListModel<>();
    
    public VentanaEstadoObra(){
        initComponents();
    } 
    public VentanaEstadoObra(Sistema unS) {
        s = unS;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        lstPresupuestos.setModel(model);
        lstGastos.setModel(model1);
        lstGastosTotales.setModel(model2);
        lstGastosTotales.setCellRenderer(new ColoresParaGastos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblObras = new javax.swing.JLabel();
        lblPropietario = new javax.swing.JLabel();
        lblComienzoObra = new javax.swing.JLabel();
        lblTotPresupuestado = new javax.swing.JLabel();
        lblCapataz = new javax.swing.JLabel();
        lblTotGastado = new javax.swing.JLabel();
        lblTotGasYaIntegrado = new javax.swing.JLabel();
        lblTotGasNoIntegrado = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblPresRubMon = new javax.swing.JLabel();
        lblRubGasObra = new javax.swing.JLabel();
        lblGasRubSelecc = new javax.swing.JLabel();
        lblCodigoColores = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        txtComienzoObra = new javax.swing.JTextField();
        txtCapataz = new javax.swing.JTextField();
        txtTotalPresupuestado = new javax.swing.JTextField();
        txtTotalGastado = new javax.swing.JTextField();
        txtTotalGastoIntegrado = new javax.swing.JTextField();
        txtTotalGastoNoIntegrado = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        txtColorPyR = new javax.swing.JTextField();
        txtPyNoR = new javax.swing.JTextField();
        txtNoPyR = new javax.swing.JTextField();
        txtNoPyNoR = new javax.swing.JTextField();
        jScrollPanePuestos = new javax.swing.JScrollPane();
        lstObras = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPresupuestos = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstGastos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstGastosTotales = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estado de Obra");
        setResizable(false);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Estado de Obra");
        lblTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(200, 20, 210, 25);

        lblObras.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblObras.setText("Obras");
        getContentPane().add(lblObras);
        lblObras.setBounds(30, 70, 60, 16);

        lblPropietario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblPropietario.setText("Propietario");
        getContentPane().add(lblPropietario);
        lblPropietario.setBounds(270, 70, 70, 16);

        lblComienzoObra.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblComienzoObra.setText("Comienzo de Obra");
        getContentPane().add(lblComienzoObra);
        lblComienzoObra.setBounds(270, 130, 110, 16);

        lblTotPresupuestado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTotPresupuestado.setText("Total Presupuestado");
        getContentPane().add(lblTotPresupuestado);
        lblTotPresupuestado.setBounds(270, 160, 120, 16);

        lblCapataz.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblCapataz.setText("Capataz");
        getContentPane().add(lblCapataz);
        lblCapataz.setBounds(270, 100, 50, 16);

        lblTotGastado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTotGastado.setText("Total Gastado");
        getContentPane().add(lblTotGastado);
        lblTotGastado.setBounds(270, 190, 90, 16);

        lblTotGasYaIntegrado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTotGasYaIntegrado.setText("Total Gastado Ya Integrado");
        getContentPane().add(lblTotGasYaIntegrado);
        lblTotGasYaIntegrado.setBounds(270, 220, 150, 16);

        lblTotGasNoIntegrado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTotGasNoIntegrado.setText("Total Gastado No Integrado");
        getContentPane().add(lblTotGasNoIntegrado);
        lblTotGasNoIntegrado.setBounds(270, 250, 150, 16);

        lblSaldo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblSaldo.setText("Saldo");
        getContentPane().add(lblSaldo);
        lblSaldo.setBounds(270, 290, 150, 16);

        lblPresRubMon.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblPresRubMon.setText("Rubros Presupuestados");
        getContentPane().add(lblPresRubMon);
        lblPresRubMon.setBounds(20, 340, 210, 16);

        lblRubGasObra.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblRubGasObra.setText("Rubros con gastos en la obra");
        getContentPane().add(lblRubGasObra);
        lblRubGasObra.setBounds(230, 340, 180, 16);

        lblGasRubSelecc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblGasRubSelecc.setText("Gastos del rubro seleccionado");
        getContentPane().add(lblGasRubSelecc);
        lblGasRubSelecc.setBounds(430, 340, 170, 16);

        lblCodigoColores.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblCodigoColores.setText("Código de colores: ");
        getContentPane().add(lblCodigoColores);
        lblCodigoColores.setBounds(60, 500, 110, 16);

        txtPropietario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(txtPropietario);
        txtPropietario.setBounds(450, 70, 100, 22);

        txtComienzoObra.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(txtComienzoObra);
        txtComienzoObra.setBounds(450, 130, 100, 22);

        txtCapataz.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(txtCapataz);
        txtCapataz.setBounds(450, 100, 100, 22);

        txtTotalPresupuestado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotalPresupuestado);
        txtTotalPresupuestado.setBounds(450, 160, 100, 22);

        txtTotalGastado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotalGastado);
        txtTotalGastado.setBounds(450, 190, 100, 22);

        txtTotalGastoIntegrado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotalGastoIntegrado);
        txtTotalGastoIntegrado.setBounds(450, 220, 100, 22);

        txtTotalGastoNoIntegrado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotalGastoNoIntegrado);
        txtTotalGastoNoIntegrado.setBounds(450, 250, 100, 22);

        txtSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtSaldo);
        txtSaldo.setBounds(450, 290, 100, 22);

        txtColorPyR.setBackground(new java.awt.Color(0, 255, 0));
        txtColorPyR.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtColorPyR.setText("Presupuestado y Reintegrado");
        getContentPane().add(txtColorPyR);
        txtColorPyR.setBounds(190, 500, 200, 22);

        txtPyNoR.setBackground(new java.awt.Color(153, 255, 153));
        txtPyNoR.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtPyNoR.setText("Presupuestado y No Reintegrado");
        getContentPane().add(txtPyNoR);
        txtPyNoR.setBounds(190, 530, 200, 22);

        txtNoPyR.setBackground(new java.awt.Color(255, 153, 0));
        txtNoPyR.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtNoPyR.setText("No Presupuestado y Reintegrado");
        getContentPane().add(txtNoPyR);
        txtNoPyR.setBounds(400, 500, 210, 22);

        txtNoPyNoR.setBackground(new java.awt.Color(255, 0, 0));
        txtNoPyNoR.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtNoPyNoR.setText("No Presupuestado y No Reintegrado");
        getContentPane().add(txtNoPyNoR);
        txtNoPyNoR.setBounds(400, 530, 210, 22);

        lstObras.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12));
        ArrayList<Obra> obras = s.getListaObras();
        DefaultListModel<String> model2 = new DefaultListModel<>();
        for (Obra o : obras) {
            model2.addElement(o.getPermiso()+" - "+o.getDireccion());
        }
        lstObras.setModel(model2);
        lstObras.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstObras.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstObrasValueChanged(evt);
            }
        });
        jScrollPanePuestos.setViewportView(lstObras);

        getContentPane().add(jScrollPanePuestos);
        jScrollPanePuestos.setBounds(20, 90, 200, 210);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 330, 610, 30);

        btnCancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(20, 560, 100, 23);

        jScrollPane1.setViewportView(lstPresupuestos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 360, 170, 130);

        lstGastos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGastosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstGastos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(230, 360, 160, 130);

        jScrollPane3.setViewportView(lstGastosTotales);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(430, 360, 180, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 170, 630, 470);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, -10, 330, 430);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 610, 430);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 370, 610, 260);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(197, 406, 420, 230);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(600, 0, 416, 400);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(600, 370, 40, 270);

        setSize(new java.awt.Dimension(652, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lstObrasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstObrasValueChanged
        
        String aux = lstObras.getSelectedValue();
        String permisoObra = (aux.substring(0,aux.indexOf(" - ")));
        Obra obra = s.buscarObra(permisoObra);
        //configuro los botones para que no sean editables
        txtPropietario.setEditable(false);
        txtCapataz.setEditable(false);
        txtComienzoObra.setEditable(false);
        txtTotalPresupuestado.setEditable(false);
        txtTotalGastado.setEditable(false);
        txtTotalGastoIntegrado.setEditable(false);
        txtTotalGastoNoIntegrado.setEditable(false);
        txtSaldo.setEditable(false);
        //cargo los datos
        txtPropietario.setText(obra.getPropietario().getNombre());
        txtCapataz.setText(obra.getCapataz().getNombre());
        txtComienzoObra.setText(Integer.toString(obra.getMes())+"/"+Integer.toString(obra.getAño()));
        txtTotalPresupuestado.setText(Integer.toString(obra.getPresupuestoTotal()));
        txtTotalGastado.setText(Integer.toString(obra.getGastoTotal()));
        txtTotalGastoIntegrado.setText(Integer.toString(obra.totalGastadoIntegrado()));
        txtTotalGastoNoIntegrado.setText(Integer.toString(obra.totalGastadoNoIntegrado()));
        txtSaldo.setText(Integer.toString(obra.getPresupuestoTotal() - obra.getGastoTotal()));
        
        //Lleno la lista de presupuestos
        ArrayList<Presupuesto> presupuestos = obra.getPresupuestos();
        model.removeAllElements();
        for (Presupuesto p : presupuestos) {
            model.addElement("\u2022 " + p.getRubro().getNombre() + " ($" + p.getMonto() + ")");
        }
 
        //Lleno la lista de rubros con gastos
        //creo una lista con todos los  rubros con gastos, por lo que voy a tener rubros repetidos
        ArrayList<String> rubros = new ArrayList<>();
        ArrayList<Gasto> gastos = obra.getGastos();
        for (Gasto g : gastos) {
            rubros.add(g.getRubro().getNombre());
        }
        model1.removeAllElements();
        //elimino los rubros repetidos y agrego la lista al model
        rubros = s.removerDuplicados(rubros);
        for (String r : rubros) {
            Rubro rubroUnico = new Rubro(r,"");
            model1.addElement(rubroUnico.getNombre());
        }
    }//GEN-LAST:event_lstObrasValueChanged

    private void lstGastosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstGastosValueChanged
        model2.removeAllElements();
        String aux = lstObras.getSelectedValue();
        String permisoObra = (aux.substring(0,aux.indexOf(" - ")));
        Obra obra = s.buscarObra(permisoObra);
        String aux2 = lstGastos.getSelectedValue();
        Rubro rubro = s.buscarRubro(aux2);
        ArrayList<Gasto> gastos = obra.getGastos();
        for(Gasto g : gastos){
            if(g.getRubro() == rubro){
                String texto = g.getNumero()+" de "+g.getMes()+"/"+g.getAño()+" "+g.getDescripcion()+ " $"+g.getMonto();
                if(s.estaPresupuesto(aux2,obra)){
                    //agrego los tipos de gastos para poder identificarlos desde la clase ColoresParaGastos
                    if(g.getSePago()){
                        texto += "(Presupuestado y Reintegrado)";
                    }else{
                        texto += "(Presupuestado y No Reintegrado)";
                    }
                }else{
                     if(g.getSePago()){
                        texto += "(No Presupuestado y Reintegrado)";
                    }else{
                        texto += "(No Presupuestado y No Reintegrado)";
                    }
                }
                model2.addElement(texto);
            }
        }
    }//GEN-LAST:event_lstGastosValueChanged

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPanePuestos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCapataz;
    private javax.swing.JLabel lblCodigoColores;
    private javax.swing.JLabel lblComienzoObra;
    private javax.swing.JLabel lblGasRubSelecc;
    private javax.swing.JLabel lblObras;
    private javax.swing.JLabel lblPresRubMon;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblRubGasObra;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotGasNoIntegrado;
    private javax.swing.JLabel lblTotGasYaIntegrado;
    private javax.swing.JLabel lblTotGastado;
    private javax.swing.JLabel lblTotPresupuestado;
    private javax.swing.JList<String> lstGastos;
    private javax.swing.JList lstGastosTotales;
    private javax.swing.JList<String> lstObras;
    private javax.swing.JList lstPresupuestos;
    private javax.swing.JTextField txtCapataz;
    private javax.swing.JTextField txtColorPyR;
    private javax.swing.JTextField txtComienzoObra;
    private javax.swing.JTextField txtNoPyNoR;
    private javax.swing.JTextField txtNoPyR;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtPyNoR;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTotalGastado;
    private javax.swing.JTextField txtTotalGastoIntegrado;
    private javax.swing.JTextField txtTotalGastoNoIntegrado;
    private javax.swing.JTextField txtTotalPresupuestado;
    // End of variables declaration//GEN-END:variables
}