//Nicolas Hobbins y Matias Medina
package Interfaz;

import Dominio.*;
import javax.swing.ImageIcon;

public class VentanaRegistroPropietario extends javax.swing.JFrame {
    private Sistema s;
    
    public VentanaRegistroPropietario(){
        initComponents();
    } 
    public VentanaRegistroPropietario(Sistema unS) {
        s = unS;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        lblRegPropietario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Propietario");
        setResizable(false);
        getContentPane().setLayout(null);

        txtNombre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        getContentPane().add(txtNombre);
        txtNombre.setBounds(130, 70, 130, 22);

        txtCedula.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        getContentPane().add(txtCedula);
        txtCedula.setBounds(130, 100, 130, 22);

        txtDireccion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(130, 130, 130, 22);

        txtCelular.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        getContentPane().add(txtCelular);
        txtCelular.setBounds(130, 160, 130, 22);

        lblRegPropietario.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblRegPropietario.setText("Registro Propietario");
        getContentPane().add(lblRegPropietario);
        lblRegPropietario.setBounds(50, 10, 170, 40);

        lblNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(20, 70, 60, 16);

        lblCedula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblCedula.setText("Cédula:");
        getContentPane().add(lblCedula);
        lblCedula.setBounds(20, 100, 70, 16);

        lblDireccion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblDireccion.setText("Dirección:");
        getContentPane().add(lblDireccion);
        lblDireccion.setBounds(20, 130, 70, 16);

        lblTelefono.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTelefono.setText("Telefono:");
        getContentPane().add(lblTelefono);
        lblTelefono.setBounds(20, 160, 100, 16);

        btnCancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(10, 210, 100, 23);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(160, 210, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 420);

        setSize(new java.awt.Dimension(291, 315));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //registrar propietario en sistema
        String nombre = txtNombre.getText();
        String cedula = txtCedula.getText();
        String direccion = txtDireccion.getText();
        String celular = txtCelular.getText();
        
        if (s.corroborarDatosPropietario(nombre, cedula, direccion, celular)) {
            s.registrarPropietario(nombre, cedula, direccion, celular);
            //mostrar se registro propietario correctamente
            javax.swing.JOptionPane.showMessageDialog(null, "Propietario registrado con éxito", "Registro exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        else {
            String msg = "";
            if(s.existeCedula(cedula)){
                msg = ": Usuario ya registrado";
            }
            javax.swing.JOptionPane.showMessageDialog(null, "Datos incorrectos"+msg, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegPropietario;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
