//Nicolas Hobbins y Matias Medina
package Interfaz;

import Dominio.*;
import javax.swing.*;
import java.util.*;

public class VentanaRegistroRubro extends javax.swing.JFrame {

    private Sistema s;
    DefaultListModel<String> model = new DefaultListModel<>();
    
    public VentanaRegistroRubro(){
        initComponents();
        lstRubros.setModel(model);
    } 
    public VentanaRegistroRubro(Sistema unS) {
        s = unS;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstRubros = new javax.swing.JList<>(model);
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        lblTitular = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Rubro");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        lblNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(10, 60, 70, 16);

        lblDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblDescripcion.setText("Descripción:");
        getContentPane().add(lblDescripcion);
        lblDescripcion.setBounds(10, 100, 80, 16);

        txtNombre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(90, 60, 360, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Rubros:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 220, 70, 16);

        txtDescripcion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(90, 100, 360, 60);

        lstRubros.setModel(model);
        ArrayList<Rubro> rubros = s.getListaRubros();
        model.removeAllElements();
        for (Rubro r : rubros) {
            model.addElement(r.getNombre());
        }
        lstRubros.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRubrosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstRubros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 220, 360, 170);

        btnCancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(20, 420, 90, 23);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(280, 180, 170, 23);

        btnModificar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnModificar.setText("Modificar Descripción");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(90, 180, 160, 23);

        lblTitular.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblTitular.setText("Registro de Rubro");
        getContentPane().add(lblTitular);
        lblTitular.setBounds(160, 20, 150, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 410);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 0, 110, 410);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 400, 520, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 400, 260, 100);

        setSize(new java.awt.Dimension(501, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //registramos el rubro en sistema
        String nombre = txtNombre.getText();
        String descripcion = txtDescripcion.getText();
        if (s.corroborarNombreRubro(nombre)) {
            s.registrarRubro(nombre, descripcion);
            ArrayList<Rubro> rubros = s.getListaRubros();
            model.removeAllElements();
            for (Rubro r : rubros) {
                model.addElement(r.getNombre());
            }
            
            txtNombre.setText("");
            txtDescripcion.setText("");
            javax.swing.JOptionPane.showMessageDialog(null, "Rubro registrado con éxito", "Registro exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String msg="";
            if(s.existeNombre(nombre)){
                msg=": Rubro ya existe";
            }
            javax.swing.JOptionPane.showMessageDialog(null, "Datos incorrectos"+msg, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String rub = lstRubros.getSelectedValue();
        Rubro rubro = s.buscarRubro(rub);
        String descripcion = txtDescripcion.getText();
        if(!descripcion.equals("")){
            rubro.setDescripcion(descripcion);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void lstRubrosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRubrosValueChanged
        String rub = lstRubros.getSelectedValue();
        Rubro rubro = s.buscarRubro(rub);
        txtNombre.setText(rubro.getNombre());
        txtDescripcion.setText(rubro.getDescripcion());
    }//GEN-LAST:event_lstRubrosValueChanged

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JList<String> lstRubros;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
