//Nicolas Hobbins y Matias Medina
package Interfaz;

import Dominio.*;
import io.ImportaDatosObra;
import javax.swing.JFileChooser;
import java.io.File;
/**
 *
 * @author matia
 */
public class VentanaOpcionesImportacion extends javax.swing.JFrame {
    private Sistema s;

    public VentanaOpcionesImportacion() {
        initComponents();
    }
    
    public VentanaOpcionesImportacion(Sistema unS) {
        s = unS;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Seleccionar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 90, 160, 23);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Importación de Obra");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 10, 240, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -10, 410, 190);

        setSize(new java.awt.Dimension(395, 183));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Crear un JFileChooser
        JFileChooser fileChooser = new JFileChooser();
        // Mostrar el diálogo de selección de archivos
        int returnVal = fileChooser.showOpenDialog(this);
        // Si el usuario selecciona un archivo
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String filePath = file.getAbsolutePath();
            if(ImportaDatosObra.importarObra(s,filePath)==2){
                javax.swing.JOptionPane.showMessageDialog(null, "Permiso ya existe", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }else{
                if(ImportaDatosObra.importarObra(s,filePath)==1){
                    javax.swing.JOptionPane.showMessageDialog(null, "Datos cargados con éxito", "Carga exitosa", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }else{
                    javax.swing.JOptionPane.showMessageDialog(null, "Cedula no Registrada", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    this.dispose();
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "No se pudo cargar los datos", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
