//Nicolas Hobbins y Matias Medina
package Interfaz;

import Dominio.*;
import javax.swing.*;
import java.util.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class VentanaRegistroObra extends JFrame
        implements Observer {
    
    private Sistema s;
    private javax.swing.Timer timer;
    private ArrayList<Presupuesto> presupuestos;
    
    public VentanaRegistroObra(){
        initComponents();
    } 
    public VentanaRegistroObra(Sistema unS) {
        s = unS;
        initComponents();
        s.addObserver(this);
        update(null,null);
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        //utilizo el timer para mantener actualizada la ventana
        timer = new javax.swing.Timer(200, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                update(null,null);
            }
        });
        timer.start();
        presupuestos = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistroObra = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblCapataces = new javax.swing.JLabel();
        lblNroPermiso = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblAños = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNroPermiso = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jScrollPanePropietarios = new javax.swing.JScrollPane();
        lstPropietarios = new javax.swing.JList<>();
        jScrollPaneCapataces = new javax.swing.JScrollPane();
        lstCapataces = new javax.swing.JList<>();
        spnrMes = new javax.swing.JSpinner();
        spnrAño = new javax.swing.JSpinner();
        jScrollPaneRubros = new javax.swing.JScrollPane();
        panelRubros = new javax.swing.JPanel();
        lblPropietarios = new javax.swing.JLabel();
        txtPresupuesto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Obra");
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        lblRegistroObra.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblRegistroObra.setText("Registro Obra");
        getContentPane().add(lblRegistroObra);
        lblRegistroObra.setBounds(320, 20, 120, 40);

        btnCancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(50, 430, 130, 23);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(590, 430, 130, 23);

        lblCapataces.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblCapataces.setText("Capataces");
        getContentPane().add(lblCapataces);
        lblCapataces.setBounds(330, 90, 60, 16);

        lblNroPermiso.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblNroPermiso.setText("Permiso Nro:");
        getContentPane().add(lblNroPermiso);
        lblNroPermiso.setBounds(600, 90, 80, 16);

        lblDireccion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblDireccion.setText("Dirección");
        getContentPane().add(lblDireccion);
        lblDireccion.setBounds(600, 170, 60, 16);

        lblAños.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblAños.setText("Comienzo Mes/Año");
        getContentPane().add(lblAños);
        lblAños.setBounds(600, 250, 110, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel11.setText("Total Presupuesto");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(600, 340, 110, 16);
        getContentPane().add(txtNroPermiso);
        txtNroPermiso.setBounds(600, 110, 64, 22);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(600, 190, 130, 22);

        lstPropietarios.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12));
        ArrayList<Propietario> propietarios = s.getListaPropietarios();
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Propietario p : propietarios) {
            model.addElement(p.getNombre());
        }
        lstPropietarios.setModel(model);
        lstPropietarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPanePropietarios.setViewportView(lstPropietarios);

        getContentPane().add(jScrollPanePropietarios);
        jScrollPanePropietarios.setBounds(50, 110, 230, 100);

        lstCapataces.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12));
        ArrayList<Capataz> capataces = s.getListaCapataces();
        DefaultListModel<String> modelo = new DefaultListModel<>();
        for (Capataz c : capataces) {
            modelo.addElement(c.getNombre());
        }
        lstCapataces.setModel(modelo);
        jScrollPaneCapataces.setViewportView(lstCapataces);

        getContentPane().add(jScrollPaneCapataces);
        jScrollPaneCapataces.setBounds(330, 110, 240, 100);
        getContentPane().add(spnrMes);
        spnrMes.setBounds(600, 270, 64, 22);
        getContentPane().add(spnrAño);
        spnrAño.setBounds(670, 270, 64, 22);

        panelRubros.setLayout(new java.awt.GridLayout((s.getListaRubros().size())/2, 2));
        jScrollPaneRubros.setViewportView(panelRubros);

        getContentPane().add(jScrollPaneRubros);
        jScrollPaneRubros.setBounds(50, 230, 520, 180);

        lblPropietarios.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblPropietarios.setText("Propietarios");
        getContentPane().add(lblPropietarios);
        lblPropietarios.setBounds(50, 90, 70, 16);

        txtPresupuesto.setEditable(false);
        getContentPane().add(txtPresupuesto);
        txtPresupuesto.setBounds(600, 360, 64, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 420);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 0, 350, 420);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 410, 420, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 380, 410, 160);

        setSize(new java.awt.Dimension(771, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        s.resetearMontosRubros();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    private class RubroListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            // este código se ejecutará al presionar el botón, obtengo cuál botón
            JButton cual = ((JButton) e.getSource());
            String rub = cual.getText();
            Rubro rubro = s.buscarRubro(rub);
            update(null,null);
            VentanaMontoRubroParaObra v = new VentanaMontoRubroParaObra(s,rubro);
            v.setVisible(true);

        }
    }
    
    
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //registrar obra en sistema
        String nombrePropietario = lstPropietarios.getSelectedValue();
        String nombreCapataz = lstCapataces.getSelectedValue();
        String permiso = txtNroPermiso.getText();
        String direccion = txtDireccion.getText();
        int año = Integer.parseInt(spnrAño.getValue().toString());
        int mes = Integer.parseInt(spnrMes.getValue().toString());
        Capataz capataz = s.buscarCapataz(nombreCapataz);
        Propietario propietario = s.buscarPropietario(nombrePropietario);
        int presupuestoTotal = s.devolverPresupuestoTotal();
        
        if (s.corroborarDatosObra(propietario, capataz, presupuestos, permiso, direccion, año, mes)) {
            s.registrarObra(propietario,capataz,presupuestos,permiso,direccion,año,mes, presupuestoTotal);
            //mostrar se registro obra correctamente
            javax.swing.JOptionPane.showMessageDialog(null, "Obra registrada con éxito", "Registro exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        else {
            String msj="";
            if(s.existePermiso(permiso)){
                msj=": Permiso ya existe";
            }
            javax.swing.JOptionPane.showMessageDialog(null, "Datos incorrectos"+msj, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
        s.resetearMontosRubros();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        s.resetearMontosRubros();
    }//GEN-LAST:event_formWindowClosed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        
    }//GEN-LAST:event_formMouseMoved

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
       
    }//GEN-LAST:event_formMouseReleased
    

    public boolean estaPresupuesto(Presupuesto presupuesto){
        boolean retorno = false;
        for (Presupuesto p : presupuestos){
            if(presupuesto.getRubro().getNombre().equals(p.getRubro().getNombre()))
                retorno = true;
        }
        return retorno;
    }

    
    @Override
    public void update(Observable o, Object obs){
        panelRubros.removeAll();
        ArrayList<Rubro> rubros = s.getListaRubros();
        int contador=0;
        int paridadRubros = 0;
        if((rubros.size())% 2 != 0){
            paridadRubros = 1;
            Rubro r = new Rubro();
            rubros.add(r);
        }
        for(int i=0;i<2;i++){
            for(int j=0;j<((rubros.size()/2)-paridadRubros);j++){
                Rubro rubro = rubros.get(contador);
                Presupuesto presupuesto = new Presupuesto(rubro,rubro.getMonto());
                JButton nuevo = new JButton(rubro.getNombre());
                nuevo.setMargin(new Insets(-5, -5, -5, -5));
                //si existe monto registrado mayor a 0 modifico el boton como se pide; de lo contrario, lo mantengo negro
                if(rubro.getMonto()>0){
                    nuevo.setBackground(Color.BLUE);
                    nuevo.setText("<html>"+nuevo.getText()+"<br>"+Integer.toString(rubro.getMonto())+"</html>");
                    if(!estaPresupuesto(presupuesto)){
                        presupuestos.add(presupuesto);
                        nuevo.addActionListener(new RubroListener());
                    }
                }else{
                    if(!rubro.getNombre().equals("")){
                        nuevo.setBackground(Color.BLACK);
                        nuevo.addActionListener(new RubroListener());
                    }
                }
                nuevo.setForeground(Color.WHITE);
                nuevo.setPreferredSize(new Dimension(40,80));
                contador++;
                
                panelRubros.add(nuevo);

                txtPresupuesto.setText(Integer.toString(s.devolverPresupuestoTotal()));
                panelRubros.revalidate();
                panelRubros.repaint();
            }
        }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPaneCapataces;
    private javax.swing.JScrollPane jScrollPanePropietarios;
    private javax.swing.JScrollPane jScrollPaneRubros;
    private javax.swing.JLabel lblAños;
    private javax.swing.JLabel lblCapataces;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNroPermiso;
    private javax.swing.JLabel lblPropietarios;
    private javax.swing.JLabel lblRegistroObra;
    private javax.swing.JList<String> lstCapataces;
    private javax.swing.JList<String> lstPropietarios;
    private javax.swing.JPanel panelRubros;
    private javax.swing.JSpinner spnrAño;
    private javax.swing.JSpinner spnrMes;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNroPermiso;
    private javax.swing.JTextField txtPresupuesto;
    // End of variables declaration//GEN-END:variables
}
