//Nicolas Hobbins y Matias Medina
package Interfaz;
import Dominio.*;
import java.util.*;
import javax.swing.*;

public class VentanaPagoGasto extends javax.swing.JFrame {
    private Sistema s;
    DefaultListModel<String> model = new DefaultListModel<>();
    
    public VentanaPagoGasto(){
        initComponents();
    } 
    public VentanaPagoGasto(Sistema unS) {
        s = unS;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        lstGastos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        lblRegistroGasto = new javax.swing.JLabel();
        lblGastos = new javax.swing.JLabel();
        lblObras = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jScrollPaneGastos = new javax.swing.JScrollPane();
        lstGastos = new javax.swing.JList<>();
        jScrollPaneObras = new javax.swing.JScrollPane();
        lstObras = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pago de Gasto");
        setResizable(false);
        getContentPane().setLayout(null);

        lblRegistroGasto.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblRegistroGasto.setText("Pago de Gastos");
        getContentPane().add(lblRegistroGasto);
        lblRegistroGasto.setBounds(220, 20, 240, 40);

        lblGastos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblGastos.setText("Gastos Impagos");
        getContentPane().add(lblGastos);
        lblGastos.setBounds(310, 90, 90, 16);

        lblObras.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblObras.setText("Obras");
        getContentPane().add(lblObras);
        lblObras.setBounds(30, 90, 70, 16);

        btnCancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(30, 330, 130, 23);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnRegistrar.setText("Registrar Pago");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(430, 330, 130, 23);

        jScrollPaneGastos.setViewportView(lstGastos);

        getContentPane().add(jScrollPaneGastos);
        jScrollPaneGastos.setBounds(310, 110, 250, 180);

        lstObras.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12));
        ArrayList<Obra> obras = s.getListaObras();
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Obra o : obras) {
            model.addElement(o.getPermiso() + " - " + o.getDireccion());
        }
        lstObras.setModel(model);
        lstObras.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstObras.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstObrasValueChanged(evt);
            }
        });
        jScrollPaneObras.setViewportView(lstObras);

        getContentPane().add(jScrollPaneObras);
        jScrollPaneObras.setBounds(30, 110, 220, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 420);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 0, 350, 420);

        setSize(new java.awt.Dimension(605, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
//        String aux = lstObras.getSelectedValue();
        //verificar que hayan elementos seleccionados
        if(lstObras.getSelectedValue()!=null || lstGastos.getSelectedValue()!=null){
            String aux = lstObras.getSelectedValue();
            String aux2 = lstGastos.getSelectedValue();
            String obr = (aux.substring(0,aux.indexOf(" - ")));
            Obra obra = s.buscarObra(obr);
            String gastoRubro = aux2.substring(0,aux2.indexOf(" ($"));
            Gasto gasto = s.buscarGasto(gastoRubro, obra);
            gasto.setSePago(true);
            actualizarModel();
            javax.swing.JOptionPane.showMessageDialog(null, "Gasto Pagado", "Pago exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "Seleccione datos", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        model.removeAllElements();
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void lstObrasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstObrasValueChanged
        actualizarModel();
        
    }//GEN-LAST:event_lstObrasValueChanged
    //metodo para actualizar la lista de gastos cada vez que se paga uno
    public void actualizarModel(){
        String aux = lstObras.getSelectedValue();
        String obr = (aux.substring(0 , aux.indexOf(" - ")));
        Obra obra = s.buscarObra(obr);
        model.removeAllElements();
        ArrayList<Gasto> gastos = obra.getGastos();
        for (Gasto g : gastos) {
            if (!g.getSePago()){
                model.addElement(g.getRubro().getNombre() + " ($" + g.getMonto() + ")");
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPaneGastos;
    private javax.swing.JScrollPane jScrollPaneObras;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblObras;
    private javax.swing.JLabel lblRegistroGasto;
    private javax.swing.JList<String> lstGastos;
    private javax.swing.JList<String> lstObras;
    // End of variables declaration//GEN-END:variables
}
