//Matías Medina y Nicolas Hobbins
package Interfaz;
import Dominio.*;

public class VentanaMontoRubroParaObra extends javax.swing.JFrame {
    private Rubro rubro;
    private Sistema s;
    
    public VentanaMontoRubroParaObra(Sistema unS, Rubro unRubro) {
        s = unS;
        initComponents();
        rubro = unRubro;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        txtMonto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Monto");
        setResizable(false);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lblTitulo.setText("Ingrese un monto");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(90, 10, 240, 40);

        btnSeleccionar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionar);
        btnSeleccionar.setBounds(250, 90, 100, 23);
        getContentPane().add(txtMonto);
        txtMonto.setBounds(50, 90, 160, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 410, 180);

        setSize(new java.awt.Dimension(409, 174));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        String montoString = txtMonto.getText();
        if(montoString.matches("\\d+")){
            int monto = Integer.parseInt(montoString);
            s.registrarPresupuesto(rubro, monto);
            rubro.setMonto(monto);
            this.dispose();
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "Datos incorrectos", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
