//Nicolas Hobbins y Matias Medina
package Interfaz;

import Dominio.*;
import javax.swing.ImageIcon;

public class VentanaRegistroCapataz extends javax.swing.JFrame {
    private Sistema s;
    
    public VentanaRegistroCapataz(){
        initComponents();
    } 
    public VentanaRegistroCapataz(Sistema unS) {
        s = unS;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtAñoIngreso = new javax.swing.JTextField();
        lblRegCapataz = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Capataz");
        setResizable(false);
        getContentPane().setLayout(null);

        txtNombre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        getContentPane().add(txtNombre);
        txtNombre.setBounds(130, 80, 130, 22);

        txtCedula.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        getContentPane().add(txtCedula);
        txtCedula.setBounds(130, 110, 130, 22);

        txtDireccion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(130, 140, 130, 22);

        txtAñoIngreso.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        getContentPane().add(txtAñoIngreso);
        txtAñoIngreso.setBounds(130, 170, 130, 22);

        lblRegCapataz.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblRegCapataz.setText("Registro Capataz");
        getContentPane().add(lblRegCapataz);
        lblRegCapataz.setBounds(60, 10, 150, 40);

        lblNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(20, 80, 60, 16);

        lblCedula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblCedula.setText("Cédula:");
        getContentPane().add(lblCedula);
        lblCedula.setBounds(20, 110, 70, 16);

        lblDireccion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblDireccion.setText("Dirección:");
        getContentPane().add(lblDireccion);
        lblDireccion.setBounds(20, 140, 70, 16);

        lblTelefono.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTelefono.setText("Año de ingreso:");
        getContentPane().add(lblTelefono);
        lblTelefono.setBounds(20, 170, 100, 16);

        btnCancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(10, 220, 90, 23);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(170, 220, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 420);

        setSize(new java.awt.Dimension(291, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //registrar capataz en sistema
        String nombre = txtNombre.getText();
        String cedula = txtCedula.getText();
        String direccion = txtDireccion.getText();
        String añoIngreso = txtAñoIngreso.getText();
        
        if (s.corroborarDatosCapataz(nombre, cedula, direccion, añoIngreso)&&(s.esNumero(txtAñoIngreso.getText()))) {
                s.registrarCapataz(nombre, cedula, direccion, Integer.parseInt(añoIngreso));
                //mostrar se registro capataz correctamente
                javax.swing.JOptionPane.showMessageDialog(null, "Capataz registrado con éxito", "Registro exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            else {
                String msg = "";
                if(s.existeCedula(cedula)){
                    msg = ": Usuario ya registrado";
                }
                javax.swing.JOptionPane.showMessageDialog(null, "Datos incorrectos"+msg, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegCapataz;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtAñoIngreso;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
