//Matías Medina y Nicolas Hobbins
package Interfaz;

import Dominio.*;
import io.ExportaDatosPersona;

public class VentanaOpcionesExportacion extends javax.swing.JFrame {
    private Sistema s;
    /**
     * Creates new form VentanaRegistroPuesto
     */
    public VentanaOpcionesExportacion() {
        initComponents();
    }
    public VentanaOpcionesExportacion(Sistema unS) {
        s = unS;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp1 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblOpciones = new javax.swing.JLabel();
        rbtnNombre = new javax.swing.JRadioButton();
        rbtnCedula = new javax.swing.JRadioButton();
        btnSeleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lblTitulo.setText("Opciones de Ordenamiento");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(30, 20, 310, 32);

        lblOpciones.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lblOpciones.setText("Seleccione una opción para ordenar");
        getContentPane().add(lblOpciones);
        lblOpciones.setBounds(40, 70, 260, 25);

        grp1.add(rbtnNombre);
        rbtnNombre.setText("Por Nombre");
        getContentPane().add(rbtnNombre);
        rbtnNombre.setBounds(70, 110, 120, 21);

        grp1.add(rbtnCedula);
        rbtnCedula.setText("Por Cédula");
        getContentPane().add(rbtnCedula);
        rbtnCedula.setBounds(70, 140, 120, 21);

        btnSeleccionar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionar);
        btnSeleccionar.setBounds(225, 140, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -10, 420, 240);

        setSize(new java.awt.Dimension(409, 232));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        
            if(rbtnCedula.isSelected()){
                try {
                    ExportaDatosPersona.exportarPorCedula(s);
                    javax.swing.JOptionPane.showMessageDialog(null, "Datos guardados con éxito", "Guardado exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(null, "No se pudo guardar los datos", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(rbtnNombre.isSelected()){
                try {
                    ExportaDatosPersona.exportarPorNombre(s);
                    javax.swing.JOptionPane.showMessageDialog(null, "Datos guardados con éxito", "Guardado exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(null, "No se pudo guardar los datos", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }else{
                System.out.println("Seleccione una opción");
            }
        
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.ButtonGroup grp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtnCedula;
    private javax.swing.JRadioButton rbtnNombre;
    // End of variables declaration//GEN-END:variables
}
