//Nicolas Hobbins y Matias Medina
package Interfaz;

import Dominio.*;
import javax.swing.*;
import java.util.*;

public class VentanaRegistroGasto extends javax.swing.JFrame {
    private Sistema s;
    
    public VentanaRegistroGasto(){
        initComponents();
    } 
    public VentanaRegistroGasto(Sistema unS) {
        s = unS;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblRegistroObra = new javax.swing.JLabel();
        lblRubros = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblAño = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblObras = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        spnrMes = new javax.swing.JSpinner();
        spnrAño = new javax.swing.JSpinner();
        jScrollPanePropietarios = new javax.swing.JScrollPane();
        lstObras = new javax.swing.JList<>();
        jScrollPaneCapataces = new javax.swing.JScrollPane();
        lstRubros = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Gasto");
        setResizable(false);
        getContentPane().setLayout(null);

        btnCancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(50, 430, 130, 23);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(500, 430, 130, 23);

        lblRegistroObra.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lblRegistroObra.setText("Registro de Gasto para Obra");
        getContentPane().add(lblRegistroObra);
        lblRegistroObra.setBounds(200, 20, 270, 40);

        lblRubros.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblRubros.setText("Rubros");
        getContentPane().add(lblRubros);
        lblRubros.setBounds(310, 90, 60, 16);

        lblDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblDescripcion.setText("Descripcion");
        getContentPane().add(lblDescripcion);
        lblDescripcion.setBounds(50, 310, 80, 16);

        lblMes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblMes.setText(" Mes");
        getContentPane().add(lblMes);
        lblMes.setBounds(530, 200, 50, 16);

        lblAño.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblAño.setText("Año");
        getContentPane().add(lblAño);
        lblAño.setBounds(530, 250, 22, 16);

        lblMonto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblMonto.setText("Monto");
        getContentPane().add(lblMonto);
        lblMonto.setBounds(530, 130, 36, 16);

        lblObras.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblObras.setText("Obras");
        getContentPane().add(lblObras);
        lblObras.setBounds(50, 90, 70, 16);
        getContentPane().add(txtMonto);
        txtMonto.setBounds(530, 150, 110, 22);
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(130, 310, 380, 90);
        getContentPane().add(spnrMes);
        spnrMes.setBounds(570, 200, 64, 22);
        getContentPane().add(spnrAño);
        spnrAño.setBounds(570, 250, 64, 22);

        lstObras.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12));
        ArrayList<Obra> obras = s.getListaObras();
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Obra o : obras) {
            model.addElement(o.getPermiso() + " - " + o.getDireccion());
        }
        lstObras.setModel(model);
        lstObras.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPanePropietarios.setViewportView(lstObras);

        getContentPane().add(jScrollPanePropietarios);
        jScrollPanePropietarios.setBounds(50, 110, 220, 180);

        lstRubros.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12));
        ArrayList<Rubro> rubros = s.getListaRubros();
        DefaultListModel<String> modelo = new DefaultListModel<>();
        for (Rubro r : rubros) {
            modelo.addElement(r.getNombre());
        }
        lstRubros.setModel(modelo);
        jScrollPaneCapataces.setViewportView(lstRubros);

        getContentPane().add(jScrollPaneCapataces);
        jScrollPaneCapataces.setBounds(310, 110, 200, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 420);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 0, 310, 420);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 410, 420, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 380, 370, 160);

        setSize(new java.awt.Dimension(717, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //registrar gasto en sistema
        if((lstObras.getSelectedIndex()!=-1)&&(lstRubros.getSelectedIndex()!=-1)){
            String aux = lstObras.getSelectedValue();
            String permisoObra = (aux.substring(0,aux.indexOf(" - ")));
            Obra obra = s.buscarObra(permisoObra);
            String nombreRubro = lstRubros.getSelectedValue();
            Rubro rubro = s.buscarRubro(nombreRubro);
            
            int mes = Integer.parseInt(spnrMes.getValue().toString());
            int año = Integer.parseInt(spnrAño.getValue().toString());
            String descripcion = txtDescripcion.getText();
            
            if (s.corroborarDatosGasto(txtMonto.getText(),mes,año,descripcion) && txtMonto.getText().matches("\\d+")) {
                int monto = Integer.parseInt(txtMonto.getText());
                //mostrar se registro gasto correctamente
                int numero = obra.agregarGastoYDevolverNumero(rubro,monto,mes,año,descripcion);
                javax.swing.JOptionPane.showMessageDialog(null, "Registro exitoso, Gasto número : "+numero, "Registro exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                limpiarPanel();
            }
            else {
                javax.swing.JOptionPane.showMessageDialog(null, "Datos incorrectos", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(null, "Datos incorrectos", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
        

    }//GEN-LAST:event_btnRegistrarActionPerformed
    //metodo para limpiar del model ciertos elementos
    public void limpiarPanel(){
        lstRubros.removeAll();
        txtMonto.setText("");
        txtDescripcion.setText("");
        spnrAño.setValue(0);
        spnrMes.setValue(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPaneCapataces;
    private javax.swing.JScrollPane jScrollPanePropietarios;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblObras;
    private javax.swing.JLabel lblRegistroObra;
    private javax.swing.JLabel lblRubros;
    private javax.swing.JList<String> lstObras;
    private javax.swing.JList<String> lstRubros;
    private javax.swing.JSpinner spnrAño;
    private javax.swing.JSpinner spnrMes;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
